export const FILRODENSWMB = {
    ID: "filrodens-world-map-builder",
    FLAGS: {
        IS_ACTIVE: "isActiveCanvas",
        HEX_DATA: "hexData",
        PARAMS: "generationParams",
    },
    TEMPLATES: {
        TOOLBAR: "modules/filrodens-world-map-builder/templates/toolbar.hbs",
    },
    DEFAULTS: {
        SEED: "FILRODEN",
        SEA_LEVEL: 0.35,
        LAT_TOP: 90,
        LAT_BOTTOM: -90,
        GLOBAL_TEMP: 0.5,
        GLOBAL_MOISTURE: 0.5,
        MAP_WIDTH: 1000,
        MAP_HEIGHT: 1000,
    },
    LIMITS: {
        HISTORY_MAX: 40,
        SNAP_THRESHOLD: 15,
        NOISE_SCALE_MIN: 100,
        NOISE_SCALE_MAX: 8000,
        NOISE_SCALE_STEP: 50,
        OVERFLOW_BUFFER: 100,
        BASELINE_DIMENSION: 1000,
        CUSTOM_BIOME_START_ID: 14,
    },
    UI: {
        RTL_LANGUAGES: ["ar", "he", "fa", "ur"],
        VISIBILITY_STATES: ["all", "gm", "none"],
        WHEEL: {
            SCALE_FACTOR: 1.05,
            ROTATION_STEP: 5,
            CAMERA_FACTOR: 1.1,
        },
        ZOOM: {
            FACTOR: 1.25,
            MIN_BOUNDS_SIZE: 400,
            PADDING_FACTOR: 1.2,
            MAX_ZOOM_SCALE: 2,
            VISUAL_PADDING: 30,
        },
        REFERENCE_IMAGE: {
            SCALE_MIN: 0.1,
            SCALE_MAX: 10,
            SCALE_FACTOR: 1.01,
        },
        REGIONAL_CROP: {
            PADDING: 50,
        },
        DEBOUNCE_MS: {
            TERRAIN: 800,
            CLIMATE: 800,
            FEATURES: 600,
        },
    },
    DISPLAY: {
        ALPHA: 0.8,
        GRID_ALPHA: 0.15,
        BIOME_ALPHA_ACTIVE: 0.85,
        BIOME_ALPHA_INACTIVE: 0.65,
        RIVER_WIDTH: 2,
        RIVER_ALPHA: 0.9,
        PIN_RADIUS: 6,
        PIN_ALPHA: 0.4,
        CONTOUR_INTERVAL: 0.1,
    },
    HYDROLOGY: {
        RIVER_DENSITY: 40,
        MAX_LAKE_SIZE: 8000,
        SPRING_ALTITUDE_OFFSET: 0.25,
        SPRING_MOISTURE_MIN: 0.45,
        MEANDER_JITTER: 0,
        MANUAL_RIVER_DEPTHS: {
            2: 0.015,
            4: 0.025,
            6: 0.035,
            8: 0.05,
        },
    },
    CLIMATE: {
        ALTITUDE_COOLING: 0.4,
        FREEZING_THRESHOLD: 0.2,
        THRESHOLDS: {
            TEMPERATURE: {
                ARCTIC: 0.2,
                SUBARCTIC: 0.4,
                TEMPERATE: 0.8,
            },
            MOISTURE: {
                ARCTIC: {
                    SNOW: 0.5,
                },
                SUBARCTIC: {
                    TUNDRA: 0.3,
                    TAIGA: 0.6,
                },
                TEMPERATE: {
                    DESERT: 0.25,
                    GRASSLAND: 0.6,
                    DECIDUOUS: 0.85,
                },
                TROPICAL: {
                    DESERT: 0.2,
                    SAVANNA: 0.4,
                    DECIDUOUS: 0.7,
                },
            },
        },
    },
    NOISE: {
        ELEVATION: { SCALE: 250, OCTAVES: 5, PERSISTENCE: 0.5, LACUNARITY: 2, EXPONENT: 1.2, STRETCH: 1.75 },
        MOISTURE: { SCALE: 500, OCTAVES: 3, PERSISTENCE: 0.6, LACUNARITY: 2, EXPONENT: 1, STRETCH: 1.2 },
        TEMPERATURE: { SCALE: 500, OCTAVES: 2, PERSISTENCE: 0.5, LACUNARITY: 2, EXPONENT: 1, STRETCH: 1 },
    },
    BIOMES: {
        // Oceans
        DEEP_OCEAN: [26, 75, 132],
        SHALLOW_OCEAN: [46, 117, 182],
        PACK_ICE: [225, 235, 240],

        // Cold
        SNOW: [240, 240, 240],
        TUNDRA: [149, 163, 164],
        TAIGA: [77, 107, 83],

        // Temperate
        GRASSLAND: [141, 163, 104],
        DECIDUOUS_FOREST: [58, 122, 70],
        TEMPERATE_RAINFOREST: [41, 92, 53],
        TEMPERATE_DESERT: [194, 178, 128],

        // Tropical
        TROPICAL_RAINFOREST: [23, 66, 32],
        SAVANNA: [196, 186, 114],
        SUBTROPICAL_DESERT: [214, 198, 137],
    },
    BIOME_IDS: {
        DEEP_OCEAN: 1,
        SHALLOW_OCEAN: 2,
        SNOW: 3,
        TUNDRA: 4,
        TAIGA: 5,
        GRASSLAND: 6,
        DECIDUOUS_FOREST: 7,
        TEMPERATE_RAINFOREST: 8,
        TEMPERATE_DESERT: 9,
        TROPICAL_RAINFOREST: 10,
        SAVANNA: 11,
        SUBTROPICAL_DESERT: 12,
        PACK_ICE: 13,
    },
    COMPENDIUM: {
        NAME: "fwmb-maps",
        LABEL: "Filroden's World Map Builder",
    },
    INFRASTRUCTURE_ICONS: {
        anchor: "FILRODENSWMB.ICONS.Anchor",
        bridge: "FILRODENSWMB.ICONS.Bridge",
        broadleaved_tree: "FILRODENSWMB.ICONS.BroadleavedTree",
        campsite: "FILRODENSWMB.ICONS.Campsite",
        cannon: "FILRODENSWMB.ICONS.Cannon",
        castle_keep: "FILRODENSWMB.ICONS.CastleKeep",
        castle: "FILRODENSWMB.ICONS.Castle",
        cave: "FILRODENSWMB.ICONS.Cave",
        cindercone_volcano_erupting: "FILRODENSWMB.ICONS.Volcano",
        circle: "FILRODENSWMB.ICONS.Circle",
        circle_outline: "FILRODENSWMB.ICONS.CircleOutline",
        circle_outline_with_dot: "FILRODENSWMB.ICONS.CircleDotOutline",
        city_gate: "FILRODENSWMB.ICONS.CityGate",
        classical_building: "FILRODENSWMB.ICONS.ClassicalBuilding",
        column_shrine: "FILRODENSWMB.ICONS.Shrine",
        conifer_tree: "FILRODENSWMB.ICONS.ConiferTree",
        dagger: "FILRODENSWMB.ICONS.Dagger",
        domed_tower: "FILRODENSWMB.ICONS.DomedTower",
        dot: "FILRODENSWMB.ICONS.Dot",
        dot_outline: "FILRODENSWMB.ICONS.DotOutline",
        dot_with_rays_down: "FILRODENSWMB.ICONS.DotRaysDown",
        dot_with_rays_left: "FILRODENSWMB.ICONS.DotRaysLeft",
        dot_with_rays_right: "FILRODENSWMB.ICONS.DotRaysRight",
        dot_with_rays_up: "FILRODENSWMB.ICONS.DotRaysUp",
        exclamation_point: "FILRODENSWMB.ICONS.ExclamationPoint",
        fence: "FILRODENSWMB.ICONS.Fence",
        flagstick_with_pennant: "FILRODENSWMB.ICONS.FlagstickPennant",
        fortress: "FILRODENSWMB.ICONS.Fortress",
        gable_roofed_shelter: "FILRODENSWMB.ICONS.GableRoofedShelter",
        geyser_from_ground: "FILRODENSWMB.ICONS.Geyser",
        gravestone: "FILRODENSWMB.ICONS.Gravestone",
        jp_landmark: "FILRODENSWMB.ICONS.JPLandmark",
        lighthouse: "FILRODENSWMB.ICONS.Lighthouse",
        map_pin: "FILRODENSWMB.ICONS.MapPin",
        map_pin_outline: "FILRODENSWMB.ICONS.MapPinOutline",
        map_pin_outline_with_dot: "FILRODENSWMB.ICONS.MapPinDotOutline",
        map_pin_with_dot: "FILRODENSWMB.ICONS.MapPinDot",
        megalith: "FILRODENSWMB.ICONS.Megalith",
        memorial_stone: "FILRODENSWMB.ICONS.MemorialStone",
        mesoamerican_pyramid: "FILRODENSWMB.ICONS.MesoamericanPyramid",
        mineshaft_profile: "FILRODENSWMB.ICONS.Mineshaft",
        obelisk: "FILRODENSWMB.ICONS.Obelisk",
        obelisk_on_plinth: "FILRODENSWMB.ICONS.ObeliskPlinth",
        observatory_dome: "FILRODENSWMB.ICONS.ObservatoryDome",
        palace: "FILRODENSWMB.ICONS.Palace",
        place_of_worship_building: "FILRODENSWMB.ICONS.Temple",
        question_mark: "FILRODENSWMB.ICONS.QuestionMark",
        shipwreck_in_water: "FILRODENSWMB.ICONS.Shipwreck",
        skull: "FILRODENSWMB.ICONS.Skull",
        wall_tent: "FILRODENSWMB.ICONS.WallTent",
    },
    REGIONS: {
        PRESETS: ["#C84B31", "#E28743", "#E8B851", "#4F7942", "#8A9A5B", "#3B8388", "#2D70B3", "#4A4E69", "#7A5C9B", "#B56576", "#A0522D", "#CC7161", "#6C7A89", "#A89F91", "#E08E79"],
    },
    LABELS: {
        DEFAULT_FONT: "Signika",
        DEFAULT_SIZE: 1,
        DEFAULT_COLOR: "#DEDCD3",
        DEFAULT_TEXT: "FILRODENSWMB.LABELS.DefaultLabel",
        PRESETS: ["#FFFFFF", "#DEDCD3", "#CEBB92", "#8A734D", "#E0F0FA", "#8DB2CC", "#2A4B66", "#1A1A1A"],
    },
    PINS: {
        DEFAULT_SCALE: 1,
    },
    TECTONICS: {
        DEFAULT_THICKNESS: 40,
        DEFAULT_STRENGTH: 0.25,
        HOTSPOT_SPACING: 35,
        HOTSPOT_DECAY: 0.85,
        BOUNDING_PADDING: 1.5,
        TYPES: {
            CONVERGENT: "convergent",
            DIVERGENT: "divergent",
            SLIP: "slip",
            HOTSPOT: "hotspot",
        },
        LABELS: {
            convergent: "FILRODENSWMB.TECTONICS.Convergent",
            divergent: "FILRODENSWMB.TECTONICS.Divergent",
            slip: "FILRODENSWMB.TECTONICS.Slip",
            hotspot: "FILRODENSWMB.TECTONICS.Hotspot",
        },
        COLORS: {
            convergent: "#ef4444",
            divergent: "#06b6d4",
            slip: "#f59e0b",
            hotspot: "#d97706",
        },
    },
    ENTITY_CONFIG: {
        decoration: { stateKey: "mapDecorations", activeKey: null, triggersTerrain: false },
        fault: { stateKey: "tectonicFaults", activeKey: "activeFaultId", triggersTerrain: true, toolCategory: "features" },
        label: { stateKey: "mapLabels", activeKey: null, triggersTerrain: false },
        pin: { stateKey: "mapPins", activeKey: null, triggersTerrain: false },
        regionLayer: { stateKey: "regionLayers", activeKey: "activeRegionLayerId", triggersTerrain: false, isLayer: true },
        river: { stateKey: "manualRivers", activeKey: "activeRiverId", triggersTerrain: true, toolCategory: "features" },
        route: { stateKey: "mapRoutes", activeKey: "activeRouteId", triggersTerrain: false, toolCategory: "infrastructure" },
    },
};
